### ISSUE TITLE
Simplify, remove duplication, official repo

### ISSUE THREAD

**Issue by galambalazs** [indrekots/smoothscroll#1]
Hey Indrek!

Author of the original library and gist here.

I migrated the code to an official github repo with bower support.

bower: smoothscroll-for-websites
https://github.com/galambalazs/smoothscroll-for-websites

I believe it's best if you unregister this fork and we converge to a single repo which is always up-to-date.

If you have ideas feel free to submit issues or PRs.

Cheers,
Balázs

**Comment by indrekots** [comment]
Hey Balázs,

Totally agree with you. Originally I created this repo because I had a client who was using *smoothscroll* and I wanted it to be available via Bower. At the time I could not find an official repo. But now that you have created one, I see no reason for having my own fork for it. Going to remove this repo.
